### PR TITLE
Even parity offers better compatibility for v2.2.

### PR DESCRIPTION
**Pull request by aequitas**
https://github.com/ndokter/dsmr_parser/issues/4

### CODE REVIEW

**Comment by ndokter** [comment]
Hey, why did you close the pull request? Seems like a good change to have settings that generally work for everyone.

**Comment by aequitas** [comment]
I wanted to include it in some other changes i'm making but i think its better of as a separate change.

BTW, can you check if on your meter a parity setting of NONE works as well? They we might switch the V4 to NONE by default. Some people have reported on the HA forum that NONE should work for their dsmr 4 meter: https://community.home-assistant.io/t/support-for-reading-dutch-smart-meter-electricity-gas-p1-port/1676

Also see: http://domoticx.com/p1-poort-slimme-meter-hardware/

Otherwise we can just create two serial profiles for v4, one for even and one for none parity or make the parity switchable like so: https://github.com/ndokter/dsmr_parser/compare/master...aequitas:logging?expand=1

**Comment by ndokter** [comment]
I will test it. And indeed if needed we can make several profiles that people can try so they don't have to try all the combinations themselves.

**Comment by ndokter** [comment]
Parity NONE doesn't work for my by default.

What do you think about having a SERIAL_SETTINGS_V4_2 which has EVEN and then a SERIAL_SETTINGS_V4_2_NONE or SERIAL_SETTINGS_V4_2_ALTERNATIVE. Not sure about the naming.

And then do the same for both v2 and v4?

**Comment by aequitas** [comment]
I think that should work. SERIAL_SETTINGS_V4_NONE naming is fine I think, until somebody starts complaining bytesize also needs to be different ;)

**Pull request merged**
