### PR TITLE
Add Iskra IE.x meters specification

### PR DESCRIPTION
**Pull request by jchevalier7**
Hey!
In Belgium they are deploying the new Iskra IE.5 and IE.7 meter which is not following **yet** the Belgian specification and I created the new 'ISKRA_IE' class.

Take note that the checksum is disabled in the code as the checksum sent by the meter is wrong, probably because the data is not complete yet.

Python tests are created and passing.
Tested with a P1 to USB cable and data are correctly read from the telegram.

### CODE REVIEW

**Comment by ndokter** [comment]
Thank you for your contribution!

**Comment by 3djc** [comment]
@ndokter , could you let us know if this PR is included in 1.2.0 release ? The date it was merged would suggest that yes, but release notes do not mention it

**Comment by 3djc** [comment]
Responding to self, it seems included, result of test run localy

EQUIPMENT_IDENTIFIER_GAS: 	 89547619	[None]
P1_MESSAGE_TIMESTAMP: 	 2023-04-05T07:58:03+00:00	[None]
ELECTRICITY_USED_TARIFF_1: 	 18.370	[kWh]
ELECTRICITY_USED_TARIFF_2: 	 43.912	[kWh]
ELECTRICITY_DELIVERED_TARIFF_1: 	 126.308	[kWh]
ELECTRICITY_DELIVERED_TARIFF_2: 	 3.603	[kWh]
ELECTRICITY_ACTIVE_TARIFF: 	 0001	[None]
CURRENT_ELECTRICITY_USAGE: 	 0.000	[kW]
CURRENT_ELECTRICITY_DELIVERY: 	 0.445	[kW]
INSTANTANEOUS_ACTIVE_POWER_L1_POSITIVE: 	 0.000	[kW]
INSTANTANEOUS_ACTIVE_POWER_L2_POSITIVE: 	 0.000	[kW]
INSTANTANEOUS_ACTIVE_POWER_L3_POSITIVE: 	 0.000	[kW]
INSTANTANEOUS_ACTIVE_POWER_L1_NEGATIVE: 	 0.363	[kW]
INSTANTANEOUS_ACTIVE_POWER_L2_NEGATIVE: 	 0.000	[kW]
INSTANTANEOUS_ACTIVE_POWER_L3_NEGATIVE: 	 0.079	[kW]
INSTANTANEOUS_VOLTAGE_L1: 	 238.7	[V]
INSTANTANEOUS_VOLTAGE_L2: 	 0.0	[V]
INSTANTANEOUS_VOLTAGE_L3: 	 242.2	[V]
INSTANTANEOUS_CURRENT_L1: 	 4	[A]
INSTANTANEOUS_CURRENT_L2: 	 0	[A]
INSTANTANEOUS_CURRENT_L3: 	 1	[A]
ACTUAL_SWITCH_POSITION: 	 1	[None]
TEXT_MESSAGE: 	 None	[None]
EQUIPMENT_IDENTIFIER: 	 None	[None]
MBUS DEVICE (channel 1)
	EQUIPMENT_IDENTIFIER: 	 None	[None]

**Comment by ndokter** [comment]
> @ndokter , could you let us know if this PR is included in 1.2.0 release ? The date it was merged would suggest that yes, but release notes do not mention it

Hi thanks for mentioning it. I have added it, and another addition to the release notes of v1.2.0!

**Pull request merged**
