### PR TITLE
Include needed PyCRC code

### LINKED ISSUE #47: Cannot install, PyCRC is missing
I'm getting the following issues when trying to install dsmr_parser:

```
$ pip3 install dsmr_parser
[...]
ERROR: Could not find a version that satisfies the requirement PyCRC<2,>=1.2 (from dsmr_parser) (from versions: 0.9.2)
ERROR: No matching distribution found for PyCRC<2,>=1.2 (from dsmr_parser)
```

Looking on PyPi I only see a lowercase version of this package, at version 0.9.2:
https://pypi.org/project/pycrc/
but I think this is a different package?

piwheels does seem to have both versions:
https://www.piwheels.org/project/pycrc/
https://www.piwheels.org/project/PyCRC/

Did the PyCRC package get removed?

Misc info, tried this on both a Pi:
```
 $ pip3 --version
pip 20.0.2 from /usr/local/lib/python3.7/dist-packages/pip (python 3.7)
``` 
And an Ubuntu machine:
```
$ pip3 --version
pip 19.3.1 from /usr/local/lib/python3.7/dist-packages/pip (python 3.7)
```

--- 
Edit: found a workaround by download the `whl` file directly from piwheels and installing that:
```
$ wget https://www.piwheels.org/simple/PyCRC/PyCRC-1.21-py2.py3-none-any.whl#sha256=61f07008dd7813888d4793dca630a6b02bc9f9b9f6f700af81cb54722dfe91d6
$ pip install PyCRC-1.21-py2.py3-none-any.whl
```

### PR DESCRIPTION
**Pull request by dupondje**
This fixes #47

### CODE REVIEW

**Comment by dupondje** [comment]
Please tag a new release after this :) So we can use dsmr_parser again!

**Comment by ndokter** [comment]
Thanks, i will make a new build

**Comment by dupondje** [comment]
We've might still improve it btw, by doing the init in the __init__ of the class instead of each run in the function. Will save us some cycles :)

**Comment by ndokter** [comment]
Alright great! 

Ive uploaded version v0.18

**Pull request merged**
