### PR TITLE
Fixed CRC calculation

### PR DESCRIPTION
**Pull request by AlexMekkering**
The CRC calculation of the telegram wasn't correct (at least for my Smartmeter (Landis + Gyr ZCF110 DSMR4.2). I did get the following errors:

> Jan 04 10:27:46 server hass[1996]: 17-01-04 10:27:46 ERROR (MainThread) [dsmr_parser.protocol] failed to parse telegram
> Jan 04 10:27:46 server hass[1996]: Traceback (most recent call last):
> Jan 04 10:27:46 server hass[1996]:   File "/var/lib/hass/deps/dsmr_parser/protocol.py", line 99, in handle_lines
> Jan 04 10:27:46 server hass[1996]:     parsed_telegram = self.telegram_parser.parse(self.telegram)
> Jan 04 10:27:46 server hass[1996]:   File "/var/lib/hass/deps/dsmr_parser/parsers.py", line 92, in parse
> Jan 04 10:27:46 server hass[1996]:     self.validate_telegram_checksum(line_values)
> Jan 04 10:27:46 server hass[1996]:   File "/var/lib/hass/deps/dsmr_parser/parsers.py", line 74, in validate_telegram_checksum
> Jan 04 10:27:46 server hass[1996]:     'Failed to perform CRC validation because the telegram is '
> Jan 04 10:27:46 server hass[1996]: dsmr_parser.exceptions.ParseError: Failed to perform CRC validation because the telegram is incomplete. The checksum and/or content values are missing.

After some analysis I found that according to the [standard](http://nbn-assets.netbeheernederland.nl/32768/?k=aHyn8n3Kk9ch_GFgG7TdJk-DFCl-ZaBOna0WUSvqYBfhdggUuSR_pbVF6YbO6SYcWv6IjNhu4-uQCkkVTjXFiJaPWY1T_KytQrYJnnVLQdYOeBw6hGWkqpyZOGTKnhpin2aQD8CS6v3rtlya3Jx2X_4JEd2NV9RcbJaN_CQNppERAvqLFctIKjWN6FCgb6bQ56M9wRdgH5N_ssdkN5VHiiiK6_ZuXzgJEzLIG9gDOALQ-Q8-qCt9dum54l-RAToBRuYVOflju8sh970jmgi1Z4wMxr9fAAxTPAw2waJPthSws_mU4WSE2o_zQu5pngCCqxkkXbGnQCBxf7ReaJ9nHvl9fvRU8igWz9hM6pCl4PdozRoAxHMhmvmO4hRsAm62sr2mdqFlfOQGYLAmwO1cNP0zZo0tnLQm6lynS5ttBEyGsUoFNrBtf81Ad74MUCo3dlTQsMKVtbrEIjR3jrrwpsJgMMy1rhG4WwmtnF-aLqLSBB8YlAcx5Hw8xBPc588OK4LMTuKWfP7DxhaAYsxEvmhUbWERFjdLVSt84PqWMhlh3_jxT6VJ1G3hX59U1QOcjSsY0MoEi3xPa8KmRbtG1Odqlnbjcdo9Q68JCQvyBlYyuEx0eh0G1LeoKu2nbnbV5FnAhNLKzotQ1EgZwpIxcO0NKJ3Ur_Q8m-ZSHyVoZK6rvKNZ4TFqFMO3wr-ICJo0&u=) the CRC should've been calculated over all telegram data from “/” to “!” including CRLF's, so I joined the lines by '\r\n' and that did the trick.
I also encountered some problems with the REs, so I simplified them into one RE which extracts the content and CRC as two different groups without using lookahead- or lookbehind assertions.

### CODE REVIEW

**Comment by ndokter** [comment]
Thank you for the fix.

I accepted it and will look into the line ending issue in depth later. Did you use one if the included clients when the CRC check occurred?

**Comment by AlexMekkering** [comment]
If I'm correct, https://github.com/ndokter/dsmr_parser/blob/061334f702774a0fdbc301b5187d601786d5aa0c/dsmr_parser/protocol.py#L77 effectively strips every line from its CRLF, so lines are passed to the parser without trailing CRLFs.

**Comment by ndokter** [comment]
You're right, and i probably did not update the asyncio implementation correctly. This behavior is different between the SerialReader and asyncio implementation.

My preferred way of fixing it is that the clients deliver the data as-is and the parsers then deal with raw bytestring with minimal/no preprocessing. SerialReader currently still accepts a list, but it maintains the line endings, because they're part of the original data.

**Comment by AlexMekkering** [comment]
I agree. Fixing the asyncio implementation to pass raw bytestrings to the parser (including line endings) would be the way to go then.

**Comment by ndokter** [comment]
Are you planning to create pull request for it? If not, it's also on my mental TODO list :)

**Comment by AlexMekkering** [comment]
I'm currently working on it ;-)

**Pull request merged**
