### PR TITLE
Q3D add CURRENT_ELECTRICITY_DELIVERY

### PR DESCRIPTION
**Pull request by Aeroid**
to avoid negative CURRENT_ELECTRICITY_USAGE

### CODE REVIEW

**Comment by dupondje** [comment]
How will it change the behaviour of the CURRENT_ELECTRICITY_USAGE value? :)
Looks good otherwise

**Comment by ndokter** [comment]
Looks good to me as well!

**Comment by dupondje** [comment]
You know if there is somewhere official documentation where it shows all the obis codes used?
Cause for example https://www.easymeter.com/downloads/products/zaehler/Q3D/Easymeter_Q3D_DE_2016-06-15.pdf does not mention the DELIVERY field.

**Comment by Aeroid** [comment]
No, I don't.

**Comment by ndokter** [comment]
> You know if there is somewhere official documentation where it shows all the obis codes used? Cause for example https://www.easymeter.com/downloads/products/zaehler/Q3D/Easymeter_Q3D_DE_2016-06-15.pdf does not mention the DELIVERY field.

These are all the links i have:
DSMR 5.0.2 https://www.netbeheernederland.nl/_upload/Files/Slimme_meter_15_a727fce1f1.pdf
DSMR 4.0 http://files.domoticaforum.eu/uploads/Smartmetering/DSMR%20v4.0%20final%20P1.pdf
Swedisch DSMR https://www.energiforetagen.se/globalassets/energiforetagen/det-erbjuder-vi/kurser-och-konferenser/elnat/branschrekommendation-lokalt-granssnitt-v2_0-201912.pdf

**Comment by ndokter** [comment]
These changes have been put into v1.4.0

**Pull request merged**
