### PR TITLE
Improve documentation asyncio

### PR DESCRIPTION
**Pull request by mjkl-gh**
I would like to add the missing documentation of the missing asyncio part of this library. I had some difficulty figuring this out for myself and would like to add this for the next person if the author likes my proposal

### CODE REVIEW

**Comment by ndokter** [comment]
Looks good. Was it still in draft mode or can i merge it?

**Comment by mjkl-gh** [comment]
It was a draft. I also wanted to include a way to return an object as `serial_reader.read_as_object()` but then I noticed `create_tcp_dsmr_reader()` passes already parsed telegrams to it's callback while the Telegram object requires unparsed telegrams and a parser

I've created something that constructs a mock-parser that returns the already parsed object and uses that create the telegram object. However, it's a bit convoluted. Did I miss something or is the Telegram Object missing a way of constructing objects straight from a dict?

**Comment by mjkl-gh** [comment]
I've added what I've implemented to read telegrams as objects with asyncio. However, it is not beautiful. If you want it you can keep it in, but it might be better to just drop it.

If that's decided I think it's ready to merge

**Comment by ndokter** [comment]
Sorry for the late response. I still want to consider the changes, but have to take the time to look at them

**Comment by ndokter** [comment]
I want to apologize that i forgot your merge request. The documentation is getting a bit long now, but it's a good addition. Thanks for your work

**Pull request merged**
