### PR TITLE
Support DSMR data read via RFXtrx with integrated P1 reader

### PR DESCRIPTION
**Pull request by rhpijnacker**
Implements #97.

Wraps the DSMRProtocol with a RFXtrx wrapper that processes the RF-headers and passes any actual DSMR packet data to the DSMR level.
Provides two extra functions `create_rfxtrx_dsmr_reader` and `create_rfxtrx_tcp_dsmr_reader`.

### CODE REVIEW

**Comment by rhpijnacker** [comment]
FYI: Also finished the [necessary updates to the DSMR integration in Home Assistant](https://github.com/rhpijnacker/core/commits/feature/dsmr-rfxtrx), so once this is published, I can open the PR on Home Assistant.

**Comment by ndokter** [comment]
Are you able to add a small unittest with an example packet that gets processed? Something like this: https://github.com/ndokter/dsmr_parser/blob/master/test/test_protocol.py

The goal is for others to more easily understand what this code is meant to do

**Comment by rhpijnacker** [comment]
Added test case with the telegram encoded as RF packets. 
Inserted some other type RF packets to make clear this can happen too.

**Comment by rhpijnacker** [comment]
Anything more you'd like me to do before this can be published?

**Comment by ndokter** [comment]
Looks good! Only some issues are occurring in the code style checks. Could you check them out?

For example:
`         while (len(data) > 0 and (packetlength := data[0]+1) <= len(data)):`

Should become
`         while (len(data) > 0 and (packetlength := data[0] + 1) <= len(data)):`

**Comment by rhpijnacker** [comment]
Fixed. Can I run these checks locally too?

**Comment by ndokter** [comment]
Im not sure because i think you need multiple runtimes for some checks. You can probably run tox (theres a tox.ini for it).

I think the Walrus operator isnt supported in the older Python versions. But i can help to fix it and release it later this week

**Comment by lowdef** [comment]
Yes you can run  the tests locally with the python version you have locally, for example if you have python 3.8 you can run `tox -e py38`.


```consoles
(venv) hanserik@famsrv1:~/projects/dsmr_parser$ gh pr checkout 98
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 9 (delta 6), reused 9 (delta 6), pack-reused 0
Unpacking objects: 100% (9/9), 1.63 KiB | 23.00 KiB/s, done.
From https://github.com/ndokter/dsmr_parser
   188cac5..7d28d0e  refs/pull/98/head -> feature/rfxtrx
Switched to branch 'feature/rfxtrx'


(venv) hanserik@famsrv1:~/projects/dsmr_parser$ tox -e py38
GLOB sdist-make: /home/hanserik/projects/dsmr_parser/setup.py
py38 recreate: /home/hanserik/projects/dsmr_parser/.tox/py38
py38 installdeps: pytest, pytest-cov, pylama, pytest-asyncio, pytest-catchlog, pytest-mock
py38 inst: /home/hanserik/projects/dsmr_parser/.tox/.tmp/package/1/dsmr-parser-0.30.zip
py38 installed: attrs==21.4.0,coverage==6.2,dsmr-parser @ file:///home/hanserik/projects/dsmr_parser/.tox/.tmp/package/1/dsmr-parser-0.30.zip,iniconfig==1.1.1,mccabe==0.6.1,packaging==21.3,pluggy==1.0.0,py==1.11.0,pycodestyle==2.8.0,pydocstyle==6.1.1,pyflakes==2.4.0,pylama==8.3.6,pyparsing==3.0.6,pyserial==3.5,pyserial-asyncio==0.6,pytest==6.2.5,pytest-asyncio==0.16.0,pytest-catchlog==1.2.2,pytest-cov==3.0.0,pytest-mock==3.6.1,pytz==2021.3,snowballstemmer==2.2.0,tailer==0.4.1,toml==0.10.2,tomli==2.0.0
py38 run-test-pre: PYTHONHASHSEED='4023878394'
py38 run-test: commands[0] | py.test --cov=dsmr_parser test
/home/hanserik/projects/dsmr_parser/.tox/py38/lib/python3.8/site-packages/_pytest/config/__init__.py:427: PytestConfigWarning: pytest-catchlog plugin has been merged into the core, please remove it from your requirements.
  warnings.warn(
======================================================================= test session starts =======================================================================
platform linux -- Python 3.8.10, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
cachedir: .tox/py38/.pytest_cache
rootdir: /home/hanserik/projects/dsmr_parser
plugins: cov-3.0.0, pylama-8.3.6, catchlog-1.2.2, asyncio-0.16.0, mock-3.6.1
collected 27 items                                                                                                                                                

test/test_parse_v2_2.py .                                                                                                                                   [  3%]
test/test_parse_v3.py .                                                                                                                                     [  7%]
test/test_parse_v4_2.py ....                                                                                                                                [ 22%]
test/test_parse_v5.py ....                                                                                                                                  [ 37%]
test/test_parser_corner_cases.py ....                                                                                                                       [ 51%]
test/test_protocol.py ..                                                                                                                                    [ 59%]
test/test_rfxtrx_protocol.py .                                                                                                                              [ 62%]
test/test_telegram.py .                                                                                                                                     [ 66%]
test/test_telegram_buffer.py .........                                                                                                                      [100%]

---------- coverage: platform linux, python 3.8.10-final-0 -----------
Name                                            Stmts   Miss Branch BrPart  Cover
---------------------------------------------------------------------------------
dsmr_parser/__init__.py                             0      0      0      0   100%
dsmr_parser/__main__.py                            35     35      8      0     0%
dsmr_parser/clients/__init__.py                     3      0      0      0   100%
dsmr_parser/clients/filereader.py                  61     61     20      0     0%
dsmr_parser/clients/protocol.py                    95     33     30      5    58%
dsmr_parser/clients/rfxtrx_protocol.py             31      9      8      0    72%
dsmr_parser/clients/serial_.py                     51     34     14      0    32%
dsmr_parser/clients/settings.py                     4      0      0      0   100%
dsmr_parser/clients/telegram_buffer.py             15      0      4      0   100%
dsmr_parser/exceptions.py                           4      0      4      0   100%
dsmr_parser/obis_name_mapping.py                    3      0      2      0   100%
dsmr_parser/obis_references.py                     49      0      0      0   100%
dsmr_parser/objects.py                            125     36     44      3    67%
dsmr_parser/parsers.py                            105      4     54      2    96%
dsmr_parser/profile_generic_specifications.py       6      0      0      0   100%
dsmr_parser/telegram_specifications.py             16      0      0      0   100%
dsmr_parser/value_types.py                         10      0      2      0   100%
---------------------------------------------------------------------------------
TOTAL                                             613    212    190     10    64%


======================================================================= 27 passed in 0.48s ========================================================================
py38 run-test: commands[1] | pylama dsmr_parser test
dsmr_parser/objects.py:182:43 E226 missing whitespace around arithmetic operator [pycodestyle]
dsmr_parser/profile_generic_specifications.py:10:5 E123 closing bracket does not match indentation of opening bracket's line [pycodestyle]
dsmr_parser/telegram_specifications.py:160:121 E501 line too long (170 > 120 characters) [pycodestyle]
ERROR: InvocationError for command /home/hanserik/projects/dsmr_parser/.tox/py38/bin/pylama dsmr_parser test (exited with code 1)
_____________________________________________________________________________ summary _____________________________________________________________________________
ERROR:   py38: commands failed

```

**Comment by rhpijnacker** [comment]
@lowdef Thanks, that helps.

Ran the updated code with py36 and py39, so should be good now.

**Comment by ndokter** [comment]
@rhpijnacker a new version is deployed with your contribution:
https://pypi.org/project/dsmr-parser/0.32/

**Pull request merged**
